### ISSUE TITLE
CHAOSScast China

### ISSUE THREAD

**Issue by LinuxSuRen** [opensource-f2f/partner#11]

**Comment by xiaoya-Esther** [comment]
CHAOSScast China LOGO：
<img width="466" alt="Chaosscast" src="https://user-images.githubusercontent.com/56542972/170270282-ec1a7037-6e26-4113-ac6b-4c93ae2c4e5b.png">

JPG
![Chaoss](https://user-images.githubusercontent.com/56542972/170270326-1e0ca2fc-9d60-42ee-a9df-f50f57151494.jpg)

PNG
![Chaoss](https://user-images.githubusercontent.com/56542972/170270653-b44e5205-527e-4179-802c-6950fe81111b.png)

**Comment by stevending1st** [comment]
https://github.com/opensource-f2f/partner/tree/master/logo/chaosschina

这个已完成
